### ISSUE TITLE
500 Error with certain vote totals when posting to /manifest endpoint

### ISSUE THREAD

**Issue by MorganLove** [votingworks/arlo#53]
Environments: Tested on current master (and on the branch for PR support multiple contests and candidates)

```
ERROR in app: Exception on /jurisdiction/jurisdiction-1/manifest [POST]
Traceback (most recent call last):
  File "/Users/morgan/.local/share/virtualenvs/arlo-cgZpGxiy/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/morgan/.local/share/virtualenvs/arlo-cgZpGxiy/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/morgan/.local/share/virtualenvs/arlo-cgZpGxiy/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/morgan/.local/share/virtualenvs/arlo-cgZpGxiy/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/morgan/.local/share/virtualenvs/arlo-cgZpGxiy/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/morgan/.local/share/virtualenvs/arlo-cgZpGxiy/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/morgan/Desktop/votingworks/arlo/app.py", line 327, in jurisdiction_manifest
    setup_next_round(election)
  File "/Users/morgan/Desktop/votingworks/arlo/app.py", line 81, in setup_next_round
    sample_sizes = sampler.get_sample_sizes(sample_results(election))
  File "/Users/morgan/Desktop/votingworks/arlo/sampler.py", line 198, in get_sample_sizes
    asns = self.get_asns()
  File "/Users/morgan/Desktop/votingworks/arlo/sampler.py", line 139, in get_asns
    asns[contest] = math.ceil((math.log(1/self.risk_limit) + (z_w / 2)) / ((p_w * z_w) + (p_r * z_l)))
ZeroDivisionError: float division by zero
127.0.0.1 - - [24/Jul/2019 11:07:35] "POST /jurisdiction/jurisdiction-1/manifest HTTP/1.1" 500 -
127.0.0.1 - - [24/Jul/2019 11:13:51] "GET /audit/status HTTP/1.1" 200 -
```

**Passing Scenarios**

1. 1 Contest 2 Choices 
a. Type 1 vote for a
b. Type 2 votes for B
c. Type 100 votes for total ballots 
d. Submit Audit settings and upload ballot manifest
Result: Able to submit form 

2. 1 Contest 3 Choices 
a. Type 1 vote for a
b. Type 2 votes for B
c. Type 3 votes for c
d. Type 100 votes for total ballots 
e. Submit Audit settings and upload ballot manifest
Result: Able to submit form 

2. 2 Contests 2 Choices 
a. Type 1 vote for a for both contests
b. Type 2 votes for B for both contests
d. Type 100 votes for total ballots 
e. Submit Audit settings and upload ballot manifest
Result: Able to submit form 

2. 2 Contest 3 Choices 
a. Type 1 vote for a for both
b. Type 2 votes for B for both
c. Type 3 votes for c for both
d. Type 100 votes for total ballots 
e. Submit Audit settings and upload ballot manifest
Result: Able to submit form 

**Failing Scenarios**

1. 1 Contest 2 Choices 
a. Type 19 vote for a
b. Type 20 votes for B
c. Type 40 votes for total ballots 
d. Submit Audit settings and upload ballot manifest
Result: Error  

2. 1 Contest 3 Choices 
a. Type 19 vote for a
b. Type 20 votes for B
c. Type 10 votes for c
d. Type 40 votes for total ballots 
e. Submit Audit settings and upload ballot manifest
Result: Error 

2. 2 Contests 2 Choices 
a. Type 19 vote for a for both contests
b. Type 20 votes for B for both contests
d. Type 40 votes for total ballots 
e. Submit Audit settings and upload ballot manifest
Result: Error

2. 2 Contest 3 Choices 
a. Type 19 vote for a for both
b. Type 20 votes for B for both
c. Type 10 votes for c for both
d. Type 40 votes for total ballots 
e. Submit Audit settings and upload ballot manifest
Result: Error

Ballot Manifest: Ballot Manifest May 2019 Election - WYANDOTTE.csv

**Comment by nikhilb4a** [comment]
Closing as completed. 

Claude analysis: 

Issue #53 is closable — every element of it has been resolved, most of them multiple code-generations ago.

The 2019 bug had three layers, and all three are gone:

The crashing code path no longer exists. The traceback runs through the original app.py monolith: POST /jurisdiction/<id>/manifest → setup_next_round → sampler.get_asns() with float math. That architecture is entirely gone — the monolith was split up in 2020, the single-jurisdiction backend it belonged to was removed (PR #830), and manifest upload no longer synchronously computes sample sizes at all (manifests process in a background worker; sample sizes are computed separately at round start).

The crash class — division by zero in the ASN formula near a tie — was fixed in the successor math, repeatedly. The formula now lives in bravo.get_expected_sample_size using Decimal arithmetic, exact ties short-circuit to an all-ballots recommendation via is_tie ([bravo.py:407-414](vscode-webview://0k4k6l6jq1j000v6br37se94obt1aph4jrn6rfigbb226lgpt5dc/server/audit_math/bravo.py#L407-L414)), zero-vote losers are explicitly skipped "to avoid invalid operation errors" ([bravo.py:69-72](vscode-webview://0k4k6l6jq1j000v6br37se94obt1aph4jrn6rfigbb226lgpt5dc/server/audit_math/bravo.py#L69-L72)), and there are dedicated commits for exactly this: "Makes audit math robust to ties and recounts" (PR #816, Nov 2020) and "BRAVO: Fix division-by-zero error" (PR #1688, Nov 2022).

The thread's actual conclusion — validate unrealistic inputs with a clear error instead of a 500 — is implemented. Ben diagnosed the root cause as vote totals inconsistent with ballots cast, and Morgan asked for an early, user-facing validation error. Today, ballot polling contest creation rejects impossible numbers with a 400: "Too many votes cast in contest: … (X votes, Y allowed)" ([contests.py:270-278](vscode-webview://0k4k6l6jq1j000v6br37se94obt1aph4jrn6rfigbb226lgpt5dc/server/api/contests.py#L270-L278)).
